INSERT INTO EXCHANGE_VALUE (ID,FROM_VALUES,TO_VALUES,CONVERSION_MULTIPLE) VALUES (10001,'USD','INR',65);
INSERT INTO EXCHANGE_VALUE (ID,FROM_VALUES,TO_VALUES,CONVERSION_MULTIPLE) VALUES (10002,'EUR','INR',75);
INSERT INTO EXCHANGE_VALUE (ID,FROM_VALUES,TO_VALUES,CONVERSION_MULTIPLE) VALUES (10003,'AUD','INR',25);
